### ISSUE TITLE
exception doesn't get caught when watching

### ISSUE THREAD

**Issue by raffomania** [philopon/gulp-elm#22]
When watching for changes, errors in the code make the compiler return an error, which somewhere gets thrown as an Exception by `q`: 

```
[13:16:29] Starting 'compile:elm'...
(node:8191) DeprecationWarning: 'root' is deprecated, use 'global'
(node:8191) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
-- SYNTAX PROBLEM - <source folder>/TagSelect.elm

I ran into something unexpected when parsing your code!

72|     let
        ^
I am looking for one of the following things:

    end of input
    whitespace



<project folder>/node_modules/q/q.js:155
                throw e;
                ^
```

This leads to the `watch` process stopping and not recompiling anything after further changes.

**Comment by bdukes** [comment]
@raffomania is this an error specific to gulp-elm, or are you also seeing this issue with other gulp plugins (e.g. if you have an error compiling Sass to CSS, would it have the same behavior)?  As I understand it, this is how Gulp 3 works (though this will change in Gulp 4).  You can work around this in a couple of ways, the simplest of which is using the [gulp-plumber plugin](https://www.npmjs.com/package/gulp-plumber) (we dynamically set the `errorHandler` option to `false` in CI, so that errors are visible, and to a function during development which triggers [gulp-notify](https://www.npmjs.com/package/gulp-notify)).

If I'm offbase and this is an error specific to gulp-elm, let us know, and we'll try to track it down.
